# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: userdb
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
