version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: userdb
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://test_db:qwe@db:5432/userdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
